const test_transcript = ["0:00  We've already done multiple videos",
"0:01 on the chain rule with multiple worked examples,",
"0:04 but what we're gonna do in this video",
"0:05 is focus on key misunderstandings that folks often have,",
"0:09 and we actually got these misunderstandings",
"0:12 from the folks who write the AP exams,",
"0:15 from the actual College Board.",
"0:17 So let's say that we are trying to take",
"0:20 the derivative of the expression.",
"0:23 So let's say we're taking the derivative",
"0:25 of the expression,",
"0:27 the natural log of sine of x.",
"0:33 So the first key misconception or misunderstanding",
"0:36 that many people have",
"0:38 is when you're dealing",
"0:39 with transcendental functions like this,",
"0:41 and transcendental functions is just a fancy word",
"0:43 for these functions like trigonometric functions,",
"0:45 logarithmic functions,",
"0:46 that don't use standard algebraic operations.",
"0:49 But when you see transcendental functions like this",
"0:51 or compositions of them,",
"0:53 many people confuse this with the product of functions.",
"0:57 So at first when they look at this,",
"0:59 they might see this as being the same",
"1:00 as the derivative with respect to x",
"1:03 of natural log of x,",
"1:06 natural log of x, times sine of x.",
"1:10 And you can see just the way that it's written,",
"1:12 they look very similar,",
"1:14 but this is the product of two functions.",
"1:17 If you said natural log of x is f of x,",
"1:21 and sine of x is g of x,",
"1:24 this is the product of sine and g of x,",
"1:26 sorry this is the product of f of x and g of x,",
"1:30 and here you would use the product rule.",
"1:33 So to actually compute this,",
"1:35 you would use the product, the product rule.",
"1:39 But this is a composition.",
"1:41 Here you have f of g of x,",
"1:44 not f of x times g of x.",
"1:47 So here you have",
"1:51 that is our g of x, it equals sine of x,",
"1:53 and then our f of g of x",
"1:56 is the natural log of sine of x.",
"1:58 So this is f of g of x,",
"2:02 f of g of x just like that.",
"2:05 If someone asks you just what f of x was,",
"2:06 well that would be natural log of x,",
"2:08 but f of g of x is natural log of our g of x,",
"2:12 which is natural log of sine of x.",
"2:14 So that's the key first thing,",
"2:15 always make sure whether you're gonna use,",
"2:18 especially with these transcendental functions,",
"2:20 that hey if this is a composition you've gotta use",
"2:23 the chain rule, not the product rule.",
"2:25 It's not the product.",
"2:26 Now sometimes you have a combination,",
"2:27 you have a product of compositions,",
"2:29 and then things get a little bit more involved.",
"2:31 But pay close attention to make sure",
"2:33 that you're not dealing with a composition.",
"2:37 Now the next misconception students have",
"2:40 is even if they recognize,",
"2:41 okay I've gotta use the chain rule,",
"2:43 sometimes it doesn't go fully to completion.",
"2:46 So let's continue using this example.",
"2:48 The chain rule here says,",
"2:50 look we have to take the derivative of the outer function",
"2:53 with respect to the inner function.",
"2:56 So if I were to say,",
"2:57 in this case, f of x is natural log of x,",
"3:00 f of g of x is this expression here.",
"3:02 So if I wanna do this first part,",
"3:04 f prime of g of x,",
"3:09 f prime of g of x,",
"3:11 well the derivative of the natural log of x",
"3:14 is one over x.",
"3:17 So the natural log, derivative of natural log of x",
"3:21 is one over x,",
"3:23 but we don't want the derivative where the input is x.",
"3:25 We want the derivative when the input is g of x.",
"3:28 So instead of it being one over x,",
"3:30 it's gonna be one over g of x.",
"3:33 One over g of x,",
"3:35 and we know that g of x is equal to sine of x.",
"3:38 That's equal to sine of x.",
"3:42 Now one key misunderstanding that the folks",
"3:44 of the College Board told us about",
"3:46 is many students stop right there.",
"3:49 They just do this first part,",
"3:50 and then they forget to multiply this second part.",
"3:53 So here we are not done.",
"3:55 We need to take this and multiply it times g prime of x.",
"3:59 And let me write this down.",
"4:00 g prime of x, what would that be?",
"4:03 Well the derivative of sine of x with respect to x,",
"4:07 well that's just going to be cosine of x,",
"4:09 cosine of x.",
"4:13 So in this example right over here,",
"4:15 the derivative is going to be,",
"4:18 let's see if I can squeeze it in over here,",
"4:20 it's going to be one over sine of x which is this part,",
"4:22 times cosine of x.",
"4:25 So let me write it down.",
"4:26 It is going to be one over sine of x,",
"4:30 we'll do that in that other color,",
"4:32 one over sine of x,",
"4:36 and then times cosine of x.",
"4:39 So once again,",
"4:40 just to make sure that you don't fall into",
"4:41 one of these misconceptions.",
"4:43 Let me box this off so it's a little bit,",
"4:46 it's a little bit cleaner.",
"4:49 So to just make sure that you don't fall",
"4:50 into one of these misconceptions here,",
"4:53 recognize the composition,",
"4:55 that this is not the product of natural log of x",
"4:58 and sine of x.",
"4:59 It's natural log of sine of x.",
"5:01 And then when you're actually applying the chain rule,",
"5:03 derivative of the outside with respect to the inside,",
"5:05 so the derivative of natural log of x is one over x,",
"5:08 so that applied when the input is g of x",
"5:11 is one over sine of x.",
"5:13 And then multiply that times the derivative",
"5:15 of the inner function.",
"5:17 So don't forget to do this right over here.",
"5:20 Now another misconception that students have,",
"5:23 is instead of doing what we just did,",
"5:26 instead of applying the chain rule like this,",
"5:27 they take the derivative of the outer function",
"5:31 with respect to the derivative of the inner function.",
"5:34 So for example,",
"5:36 they would compute this,",
"5:38 f prime of g prime of x,",
"5:42 f prime of g prime of x.",
"5:46 Which in this case, f prime of x is one over x,",
"5:50 but if the input is g prime of x,",
"5:52 g prime of x is cosine of x.",
"5:55 So many students end up doing this",
"5:57 where they take the derivative of the outside,",
"6:01 and they apply the input into that,",
"6:04 they use the derivative of the inside function.",
"6:07 This is not right.",
"6:10 Be very careful that you're not doing that.",
"6:12 You do the derivative of the outside function",
"6:13 with respect to the inside function,",
"6:15 not taking it's derivative,",
"6:17 and then multiply, don't forget to multiply,",
"6:19 times the derivative of the inside function here.",
"6:24 So hopefully that helps a little bit.",
"6:25 If all of this looks completely foreign to you,",
"6:27 I encourage you to watch the whole series",
"6:29 of chain rule introductory videos",
"6:31 and worked examples we have.",
"6:32 This is just a topping on top of that",
"6:35 to make sure that you don't fall into these misconceptions",
"6:37 of applying the product rule",
"6:39 when you really need to be applying the chain rule",
"6:41 or forgetting to do part of the chain rule,",
"6:43 multiplying by g prime of x,",
"6:45 or evaluating f prime of g prime of x.",
"6:49 So hopefully that helps."]

module.exports = {
  test_transcript
}
